apiVersion: v1
kind: ConfigMap
metadata:
  name: staging-pgbouncer
  namespace: staging
data:
  userlist.txt: |
   "staging-joe" "Staging2423rfwfa131dsdrce"
   "staging-han" "Staginga2421eJFiwf4ffwew"
   "staging-zeus" "Staginga03421roiF43R3FW2"

  pgbouncer.ini: |
   [databases]
   * = host=192.168.20.200 port=5432

   [users]

   [pgbouncer]
   logfile = /var/log/pgbouncer/pgbouncer.log
   pidfile =
   listen_addr = *
   listen_port = 5432
   unix_socket_dir = /run/postgresql
   unix_socket_mode = 0777
   unix_socket_group = postgres
   auth_type = any
   auth_file = /etc/pgbouncer/userlist.txt
   pool_mode = session
   server_reset_query = DISCARD ALL
   ignore_startup_parameters = extra_float_digits
   max_client_conn = 800
   default_pool_size = 40
   server_idle_timeout = 0
 
