apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: staging-pgbouncer
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 4
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 50%
  template:
    metadata:
      labels:
        app: staging-pgbouncer
        env: staging
    spec:
      containers:
      - name: staging-pgbouncer
        image: asia.gcr.io/zeus-007/zeus-pgbouncer:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        resources:
            requests:
               cpu: "300m"
               memory: "400Mi"
            limits:
               cpu: "1200m"
               memory: "1200Mi"       
        readinessProbe:
          tcpSocket:
              port: 5432
          initialDelaySeconds: 8
          periodSeconds: 5
        livenessProbe:
           tcpSocket:
              port: 5432
           initialDelaySeconds: 8
           periodSeconds: 5
        lifecycle: # (real) zero-downtime for rolling deployment
          preStop:
            exec:
              command: ["sh", "-c", "sleep 180"]
        volumeMounts:
        - name: staging-pgbouncer
          mountPath: /etc/pgbouncer/ # mount config pgbouncher
          readOnly: true      
      volumes:
      - name: staging-pgbouncer
        configMap:
          name: staging-pgbouncer # place ConfigMap pgbouncher name   
---
# service
apiVersion: v1
kind: Service
metadata:
  name: staging-pgbouncer
  namespace: staging
  labels:
    app: staging-pgbouncer
spec:
  selector:
    app: staging-pgbouncer
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
